version: '3.9'

services:
  user-service:
    image: tdixon05/user-service:latest
    ports:
      - "80:5000"  # Map port 5000 inside the container to port 80 for external access
    environment:
      - ENV=production
    deploy:
      replicas: 3  # Add replicas for load balancing
      resources:
        limits:
          cpus: "1"
          memory: "512M"
      restart_policy:
        condition: on-failure

  product-service:
    image: tdixon05/product-service:latest
    ports:
      - "81:5000"
    environment:
      - ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: "512M"
      restart_policy:
        condition: on-failure

  order-service:
    image: tdixon05/order-service:latest
    ports:
      - "82:5000"
    environment:
      - ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: "512M"
      restart_policy:
        condition: on-failure
